# Generated by Django 3.1.1 on 2020-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модель принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фирмы')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Логотип')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('printerModel', models.ManyToManyField(to='printer.PrinterModel', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Фирма принтера',
                'verbose_name_plural': 'Фирмы принтеров',
            },
        ),
    ]
