# Generated by Django 3.1.1 on 2020-11-03 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название модели')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Модель принтера',
                'verbose_name_plural': 'Модель принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус принтера',
                'verbose_name_plural': 'Статусы принтеров',
            },
        ),
        migrations.CreateModel(
            name='PrinterFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фирмы')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Логотип')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('printerModel', models.ManyToManyField(to='printer.PrinterModel', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Фирма принтера',
                'verbose_name_plural': 'Фирмы принтеров',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Имя принтера')),
                ('ip_adress', models.CharField(max_length=50, unique=True, verbose_name='Ip-адрес')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='printer.printermodel', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.CreateModel(
            name='JurnalPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apper', models.CharField(max_length=100, unique=True, verbose_name='Обращение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.room', verbose_name='Кабинет')),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printer', verbose_name='Серийный номер принтера')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.printerstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Журнал принтера',
                'verbose_name_plural': 'Журналы принтеров',
            },
        ),
    ]
