# Generated by Django 3.1.1 on 2020-11-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='printer.category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
