# Generated by Django 3.1.1 on 2020-11-03 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_printerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя принтера')),
                ('serialNumber', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.category', verbose_name='Категория')),
                ('printerModel', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='printer.printermodel', verbose_name='Модель принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
    ]
