# Generated by Django 3.1.1 on 2020-11-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_auto_20201103_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnalprinter',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
