# Generated by Django 3.1.1 on 2020-11-04 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_auto_20201103_2320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrinterStatus',
            new_name='Status',
        ),
    ]
