# Generated by Django 3.1.1 on 2020-11-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_auto_20201104_1026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='PrinterStatus',
        ),
    ]
